# Generated by Django 3.1.5 on 2021-03-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
    ]
