# Generated by Django 3.1.5 on 2021-03-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('phone_no', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=150)),
                ('DOJ', models.CharField(max_length=30)),
                ('remark', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_staff',
            },
        ),
    ]
