# Generated by Django 3.1.5 on 2021-03-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tbl_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_staff',
            old_name='DOJ',
            new_name='doj',
        ),
        migrations.RenameField(
            model_name='tbl_staff',
            old_name='phone_no',
            new_name='phoneno',
        ),
    ]
