# Generated by Django 3.1.5 on 2021-03-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210319_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('staff_id', models.CharField(max_length=30)),
                ('dept_id', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tbl_doctor',
            },
        ),
    ]
