# Generated by Django 3.1.5 on 2021-03-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tbl_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_doctor',
            name='department',
        ),
    ]
