# Generated by Django 3.1.5 on 2021-03-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_tbl_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doctor',
            name='phoneno',
            field=models.CharField(default='121234', max_length=30),
            preserve_default=False,
        ),
    ]
