# Generated by Django 3.1.5 on 2021-03-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tbl_doctor_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_opdays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.CharField(max_length=30)),
                ('doctor_id', models.CharField(max_length=40)),
                ('days', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_opdays',
            },
        ),
    ]
