# Generated by Django 3.1.5 on 2021-03-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tbl_opdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_opdays',
            name='dept_id',
            field=models.CharField(default='211', max_length=40),
            preserve_default=False,
        ),
    ]
