# Generated by Django 3.1.5 on 2021-04-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tbl_opticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_id', models.CharField(max_length=30)),
                ('op_id', models.CharField(max_length=40)),
                ('patient_id', models.CharField(max_length=30)),
                ('doctor_id', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=150)),
                ('diagnosis', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tbl_diagnosis',
            },
        ),
    ]
