# Generated by Django 3.1.5 on 2021-04-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_tbl_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_labtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=30)),
                ('op_id', models.CharField(max_length=40)),
                ('patient_id', models.CharField(max_length=30)),
                ('testname', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tbl_labtest',
            },
        ),
    ]
