# Generated by Django 3.1.1 on 2021-04-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_tbl_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_staff',
            name='status',
            field=models.CharField(default='not', max_length=30),
            preserve_default=False,
        ),
    ]
