# Generated by Django 3.1.1 on 2021-04-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_tbl_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_patient',
            name='status',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
    ]
