# Generated by Django 3.1.1 on 2021-04-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210410_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_medicine',
            name='patient_id',
            field=models.CharField(default='k', max_length=30),
            preserve_default=False,
        ),
    ]
